### ISSUE TITLE
Member's consumptions list is missing values in "Amount" column

### ISSUE THREAD

**Issue by sloschert** [arbeitszeit/arbeitszeitapp#921]
In the view of a member's private consumptions (`/member/consumptions`) the values of the "Amount" column are empty. In this column should appear the number of units consumed per consumption transaction. 

![image](https://github.com/arbeitszeit/arbeitszeitapp/assets/61537351/32b600e0-af7b-481a-a79a-fe13af278e09)

**Comment by rhklee** [comment]
I suppose here 
https://github.com/arbeitszeit/arbeitszeitapp/blob/2997c726f59fb66db49db638b21d95a0f522d51d/arbeitszeit_flask/templates/member/consumptions.html#L42
it should be `consumption.consumption_amount` instead. Since the view model has the property
https://github.com/arbeitszeit/arbeitszeitapp/blob/2997c726f59fb66db49db638b21d95a0f522d51d/arbeitszeit_web/www/presenters/private_consumptions_presenter.py#L38

**Comment by sloschert** [comment]
That looks accurate, thanks! Feel free to fork and create a pull request (https://github.com/arbeitszeit/arbeitszeitapp#contributing-to-the-source-code)
